# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28b228fa880c0565e1494c0711950923c08ec5091e48fd6451a009f080819563686fc292c2ce45eac3d77ce04182ff0d0c7a77e787fd98ee1b25a4df5c68de73

test:
  secret_key_base: 9b067f34683d1a5f5ab44a1fe03a9004737e925c52241f845e503576125c66f5ef58060cee815bd3d6befabaf47606036b95b2106b3782ddf8f512b98a5dc6d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
